model_id: "openai/whisper-tiny"
language: "en"
task: "transcribe"
fp16: true

eval_sets:
  - name: "dummy"
    path: "hf-internal-testing/librispeech_asr_dummy"
    splits:
      - name: "validation"
        num_samples: 10

eval_dataset_args:
  split: "VALIDATION"
  max_samples: 10

output_dir: "outputs/inference_test_fp16"
