# Train Config
# Define your datasets here.

train_sets:
  - name: "librispeech-clean-100"
    path: "librispeech_asr"
    subset: "clean.100"
    splits:
      - name: "train.100"
        num_samples: 28539
    transcript_template: "{{text}}"

val_sets:
  - name: "librispeech-clean-dev"
    path: "librispeech_asr"
    subset: "clean"
    splits:
      - name: "validation"
        num_samples: 2703
    transcript_template: "{{text}}"

test_sets:
  - name: "librispeech-clean-test"
    path: "librispeech_asr"
    subset: "clean"
    splits:
      - name: "test"
        num_samples: 2620
    transcript_template: "{{text}}"
