# Fine-tuning config
model_id: "openai/whisper-medium"
language: "en"
task: "transcribe"

train_sets:
  - name: "voxpopuli-en"
    streaming: true

train_dataset_args:
  max_audio_duration_secs: 30

val_sets:
  - name: "voxpopuli-en"
    streaming: true

val_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

eval_sets:
  - name: "voxpopuli-en"
    streaming: true
  - name: "voxpopuli-en-accented"
    streaming: true

eval_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

# Data scaling
data_fractions: [1.0]
num_subsets: 1

target_modules:
  - "proj_out"

# Training
output_dir: "outputs/voxpopuli/002/002_s"
num_epochs: 1
batch_size: 16
grad_accum_steps: 1
learning_rate: 1e-5
warmup_steps: 50
fp16: true
seed: 42
dataloader_num_workers: 8
strict_reproducibility: true

weight_decay: 0.1

# Evaluation
eval_steps: 2000
eval_batch_size: 16
