# Fine-tuning config 
model_id: "openai/whisper-medium"
language: "en"
task: "transcribe"

train_sets:
  - name: "speechcolab-gigaspeech-m"
    streaming: false

train_dataset_args:
  max_audio_duration_secs: 30

val_sets:
  - name: "speechcolab-gigaspeech-m"
    streaming: false

val_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

eval_sets:
  - name: "speechcolab-gigaspeech-m"
    streaming: false

eval_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

# Data scaling
data_fractions: [0.5]
num_subsets: 1

# LoRA
lora_config:
  r: 64                  # Rank
  lora_alpha: 128        # Alpha scaling
  lora_dropout: 0.1     # Dropout probability
  init_blocks:
    - ["proj_out", "layers.23"]
    - ["layers.22"]
    - ["layers.21"]
    - ["layers.20"]
    - ["layers.19"]
    - ["layers.18"]
    - ["layers.17"]
    - ["layers.16"]
    - ["layers.15"]
    - ["layers.14"]
    - ["layers.13"]
    - ["layers.12"]
    - ["layers.11"]
    - ["layers.10"]
    - ["layers.9"]
    - ["layers.8"]
    - ["layers.7"]
    - ["layers.6"]
    - ["layers.5"]
    - ["layers.4"]
    - ["layers.3"]
    - ["layers.2"]
    - ["layers.1"]
    - ["layers.0"]

target_modules:
- "proj_out"
- "model.decoder.layers.23.self_attn.q_proj"
- "model.decoder.layers.23.self_attn.k_proj"
- "model.decoder.layers.23.self_attn.v_proj"
- "model.decoder.layers.23.self_attn.out_proj"
- "model.decoder.layers.23.encoder_attn.q_proj"
- "model.decoder.layers.23.encoder_attn.k_proj"
- "model.decoder.layers.23.encoder_attn.v_proj"
- "model.decoder.layers.23.encoder_attn.out_proj"
- "model.decoder.layers.23.fc1"
- "model.decoder.layers.23.fc2"
- "model.decoder.layers.22.self_attn.q_proj"
- "model.decoder.layers.22.self_attn.k_proj"
- "model.decoder.layers.22.self_attn.v_proj"
- "model.decoder.layers.22.self_attn.out_proj"
- "model.decoder.layers.22.encoder_attn.q_proj"
- "model.decoder.layers.22.encoder_attn.k_proj"
- "model.decoder.layers.22.encoder_attn.v_proj"
- "model.decoder.layers.22.encoder_attn.out_proj"
- "model.decoder.layers.22.fc1"
- "model.decoder.layers.22.fc2"
- "model.decoder.layers.21.self_attn.q_proj"
- "model.decoder.layers.21.self_attn.k_proj"
- "model.decoder.layers.21.self_attn.v_proj"
- "model.decoder.layers.21.self_attn.out_proj"
- "model.decoder.layers.21.encoder_attn.q_proj"
- "model.decoder.layers.21.encoder_attn.k_proj"
- "model.decoder.layers.21.encoder_attn.v_proj"
- "model.decoder.layers.21.encoder_attn.out_proj"
- "model.decoder.layers.21.fc1"
- "model.decoder.layers.21.fc2"
- "model.decoder.layers.20.self_attn.q_proj"
- "model.decoder.layers.20.self_attn.k_proj"
- "model.decoder.layers.20.self_attn.v_proj"
- "model.decoder.layers.20.self_attn.out_proj"
- "model.decoder.layers.20.encoder_attn.q_proj"
- "model.decoder.layers.20.encoder_attn.k_proj"
- "model.decoder.layers.20.encoder_attn.v_proj"
- "model.decoder.layers.20.encoder_attn.out_proj"
- "model.decoder.layers.20.fc1"
- "model.decoder.layers.20.fc2"
- "model.decoder.layers.19.self_attn.q_proj"
- "model.decoder.layers.19.self_attn.k_proj"
- "model.decoder.layers.19.self_attn.v_proj"
- "model.decoder.layers.19.self_attn.out_proj"
- "model.decoder.layers.19.encoder_attn.q_proj"
- "model.decoder.layers.19.encoder_attn.k_proj"
- "model.decoder.layers.19.encoder_attn.v_proj"
- "model.decoder.layers.19.encoder_attn.out_proj"
- "model.decoder.layers.19.fc1"
- "model.decoder.layers.19.fc2"
- "model.decoder.layers.18.self_attn.q_proj"
- "model.decoder.layers.18.self_attn.k_proj"
- "model.decoder.layers.18.self_attn.v_proj"
- "model.decoder.layers.18.self_attn.out_proj"
- "model.decoder.layers.18.encoder_attn.q_proj"
- "model.decoder.layers.18.encoder_attn.k_proj"
- "model.decoder.layers.18.encoder_attn.v_proj"
- "model.decoder.layers.18.encoder_attn.out_proj"
- "model.decoder.layers.18.fc1"
- "model.decoder.layers.18.fc2"
- "model.decoder.layers.17.self_attn.q_proj"
- "model.decoder.layers.17.self_attn.k_proj"
- "model.decoder.layers.17.self_attn.v_proj"
- "model.decoder.layers.17.self_attn.out_proj"
- "model.decoder.layers.17.encoder_attn.q_proj"
- "model.decoder.layers.17.encoder_attn.k_proj"
- "model.decoder.layers.17.encoder_attn.v_proj"
- "model.decoder.layers.17.encoder_attn.out_proj"
- "model.decoder.layers.17.fc1"
- "model.decoder.layers.17.fc2"
- "model.decoder.layers.16.self_attn.q_proj"
- "model.decoder.layers.16.self_attn.k_proj"
- "model.decoder.layers.16.self_attn.v_proj"
- "model.decoder.layers.16.self_attn.out_proj"
- "model.decoder.layers.16.encoder_attn.q_proj"
- "model.decoder.layers.16.encoder_attn.k_proj"
- "model.decoder.layers.16.encoder_attn.v_proj"
- "model.decoder.layers.16.encoder_attn.out_proj"
- "model.decoder.layers.16.fc1"
- "model.decoder.layers.16.fc2"
- "model.decoder.layers.15.self_attn.q_proj"
- "model.decoder.layers.15.self_attn.k_proj"
- "model.decoder.layers.15.self_attn.v_proj"
- "model.decoder.layers.15.self_attn.out_proj"
- "model.decoder.layers.15.encoder_attn.q_proj"
- "model.decoder.layers.15.encoder_attn.k_proj"
- "model.decoder.layers.15.encoder_attn.v_proj"
- "model.decoder.layers.15.encoder_attn.out_proj"
- "model.decoder.layers.15.fc1"
- "model.decoder.layers.15.fc2"
- "model.decoder.layers.14.self_attn.q_proj"
- "model.decoder.layers.14.self_attn.k_proj"
- "model.decoder.layers.14.self_attn.v_proj"
- "model.decoder.layers.14.self_attn.out_proj"
- "model.decoder.layers.14.encoder_attn.q_proj"
- "model.decoder.layers.14.encoder_attn.k_proj"
- "model.decoder.layers.14.encoder_attn.v_proj"
- "model.decoder.layers.14.encoder_attn.out_proj"
- "model.decoder.layers.14.fc1"
- "model.decoder.layers.14.fc2"
- "model.decoder.layers.13.self_attn.q_proj"
- "model.decoder.layers.13.self_attn.k_proj"
- "model.decoder.layers.13.self_attn.v_proj"
- "model.decoder.layers.13.self_attn.out_proj"
- "model.decoder.layers.13.encoder_attn.q_proj"
- "model.decoder.layers.13.encoder_attn.k_proj"
- "model.decoder.layers.13.encoder_attn.v_proj"
- "model.decoder.layers.13.encoder_attn.out_proj"
- "model.decoder.layers.13.fc1"
- "model.decoder.layers.13.fc2"
- "model.decoder.layers.12.self_attn.q_proj"
- "model.decoder.layers.12.self_attn.k_proj"
- "model.decoder.layers.12.self_attn.v_proj"
- "model.decoder.layers.12.self_attn.out_proj"
- "model.decoder.layers.12.encoder_attn.q_proj"
- "model.decoder.layers.12.encoder_attn.k_proj"
- "model.decoder.layers.12.encoder_attn.v_proj"
- "model.decoder.layers.12.encoder_attn.out_proj"
- "model.decoder.layers.12.fc1"
- "model.decoder.layers.12.fc2"
- "model.decoder.layers.11.self_attn.q_proj"
- "model.decoder.layers.11.self_attn.k_proj"
- "model.decoder.layers.11.self_attn.v_proj"
- "model.decoder.layers.11.self_attn.out_proj"
- "model.decoder.layers.11.encoder_attn.q_proj"
- "model.decoder.layers.11.encoder_attn.k_proj"
- "model.decoder.layers.11.encoder_attn.v_proj"
- "model.decoder.layers.11.encoder_attn.out_proj"
- "model.decoder.layers.11.fc1"
- "model.decoder.layers.11.fc2"
- "model.decoder.layers.10.self_attn.q_proj"
- "model.decoder.layers.10.self_attn.k_proj"
- "model.decoder.layers.10.self_attn.v_proj"
- "model.decoder.layers.10.self_attn.out_proj"
- "model.decoder.layers.10.encoder_attn.q_proj"
- "model.decoder.layers.10.encoder_attn.k_proj"
- "model.decoder.layers.10.encoder_attn.v_proj"
- "model.decoder.layers.10.encoder_attn.out_proj"
- "model.decoder.layers.10.fc1"
- "model.decoder.layers.10.fc2"
- "model.decoder.layers.9.self_attn.q_proj"
- "model.decoder.layers.9.self_attn.k_proj"
- "model.decoder.layers.9.self_attn.v_proj"
- "model.decoder.layers.9.self_attn.out_proj"
- "model.decoder.layers.9.encoder_attn.q_proj"
- "model.decoder.layers.9.encoder_attn.k_proj"
- "model.decoder.layers.9.encoder_attn.v_proj"
- "model.decoder.layers.9.encoder_attn.out_proj"
- "model.decoder.layers.9.fc1"
- "model.decoder.layers.9.fc2"
- "model.decoder.layers.8.self_attn.q_proj"
- "model.decoder.layers.8.self_attn.k_proj"
- "model.decoder.layers.8.self_attn.v_proj"
- "model.decoder.layers.8.self_attn.out_proj"
- "model.decoder.layers.8.encoder_attn.q_proj"
- "model.decoder.layers.8.encoder_attn.k_proj"
- "model.decoder.layers.8.encoder_attn.v_proj"
- "model.decoder.layers.8.encoder_attn.out_proj"
- "model.decoder.layers.8.fc1"
- "model.decoder.layers.8.fc2"
- "model.decoder.layers.7.self_attn.q_proj"
- "model.decoder.layers.7.self_attn.k_proj"
- "model.decoder.layers.7.self_attn.v_proj"
- "model.decoder.layers.7.self_attn.out_proj"
- "model.decoder.layers.7.encoder_attn.q_proj"
- "model.decoder.layers.7.encoder_attn.k_proj"
- "model.decoder.layers.7.encoder_attn.v_proj"
- "model.decoder.layers.7.encoder_attn.out_proj"
- "model.decoder.layers.7.fc1"
- "model.decoder.layers.7.fc2"
- "model.decoder.layers.6.self_attn.q_proj"
- "model.decoder.layers.6.self_attn.k_proj"
- "model.decoder.layers.6.self_attn.v_proj"
- "model.decoder.layers.6.self_attn.out_proj"
- "model.decoder.layers.6.encoder_attn.q_proj"
- "model.decoder.layers.6.encoder_attn.k_proj"
- "model.decoder.layers.6.encoder_attn.v_proj"
- "model.decoder.layers.6.encoder_attn.out_proj"
- "model.decoder.layers.6.fc1"
- "model.decoder.layers.6.fc2"
- "model.decoder.layers.5.self_attn.q_proj"
- "model.decoder.layers.5.self_attn.k_proj"
- "model.decoder.layers.5.self_attn.v_proj"
- "model.decoder.layers.5.self_attn.out_proj"
- "model.decoder.layers.5.encoder_attn.q_proj"
- "model.decoder.layers.5.encoder_attn.k_proj"
- "model.decoder.layers.5.encoder_attn.v_proj"
- "model.decoder.layers.5.encoder_attn.out_proj"
- "model.decoder.layers.5.fc1"
- "model.decoder.layers.5.fc2"
- "model.decoder.layers.4.self_attn.q_proj"
- "model.decoder.layers.4.self_attn.k_proj"
- "model.decoder.layers.4.self_attn.v_proj"
- "model.decoder.layers.4.self_attn.out_proj"
- "model.decoder.layers.4.encoder_attn.q_proj"
- "model.decoder.layers.4.encoder_attn.k_proj"
- "model.decoder.layers.4.encoder_attn.v_proj"
- "model.decoder.layers.4.encoder_attn.out_proj"
- "model.decoder.layers.4.fc1"
- "model.decoder.layers.4.fc2"
- "model.decoder.layers.3.self_attn.q_proj"
- "model.decoder.layers.3.self_attn.k_proj"
- "model.decoder.layers.3.self_attn.v_proj"
- "model.decoder.layers.3.self_attn.out_proj"
- "model.decoder.layers.3.encoder_attn.q_proj"
- "model.decoder.layers.3.encoder_attn.k_proj"
- "model.decoder.layers.3.encoder_attn.v_proj"
- "model.decoder.layers.3.encoder_attn.out_proj"
- "model.decoder.layers.3.fc1"
- "model.decoder.layers.3.fc2"
- "model.decoder.layers.2.self_attn.q_proj"
- "model.decoder.layers.2.self_attn.k_proj"
- "model.decoder.layers.2.self_attn.v_proj"
- "model.decoder.layers.2.self_attn.out_proj"
- "model.decoder.layers.2.encoder_attn.q_proj"
- "model.decoder.layers.2.encoder_attn.k_proj"
- "model.decoder.layers.2.encoder_attn.v_proj"
- "model.decoder.layers.2.encoder_attn.out_proj"
- "model.decoder.layers.2.fc1"
- "model.decoder.layers.2.fc2"
- "model.decoder.layers.1.self_attn.q_proj"
- "model.decoder.layers.1.self_attn.k_proj"
- "model.decoder.layers.1.self_attn.v_proj"
- "model.decoder.layers.1.self_attn.out_proj"
- "model.decoder.layers.1.encoder_attn.q_proj"
- "model.decoder.layers.1.encoder_attn.k_proj"
- "model.decoder.layers.1.encoder_attn.v_proj"
- "model.decoder.layers.1.encoder_attn.out_proj"
- "model.decoder.layers.1.fc1"
- "model.decoder.layers.1.fc2"
- "model.decoder.layers.0.self_attn.q_proj"
- "model.decoder.layers.0.self_attn.k_proj"
- "model.decoder.layers.0.self_attn.v_proj"
- "model.decoder.layers.0.self_attn.out_proj"
- "model.decoder.layers.0.encoder_attn.q_proj"
- "model.decoder.layers.0.encoder_attn.k_proj"
- "model.decoder.layers.0.encoder_attn.v_proj"
- "model.decoder.layers.0.encoder_attn.out_proj"
- "model.decoder.layers.0.fc1"
- "model.decoder.layers.0.fc2"

# Training
output_dir: "outputs/gigaspeech/007/0071/data_scaling"
num_epochs: 1
batch_size: 16
grad_accum_steps: 1
learning_rate: 1e-5
warmup_ratio: 0.01
fp16: true
data_seed: 42
dataloader_num_workers: 8
strict_reproducibility: true

# Evaluation
eval_steps: 1000
eval_batch_size: 16
