# Fine-tuning config 
model_id: "openai/whisper-medium"
language: "en"
task: "transcribe"

train_sets:
  - name: "speechcolab-gigaspeech-m"

train_dataset_args:
  max_audio_duration_secs: 30

val_sets:
  - name: "speechcolab-gigaspeech-m"

val_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

eval_sets:
  - name: "speechcolab-gigaspeech-m"

eval_dataset_args:
  max_audio_duration_secs: 30
  max_samples: -1

# Data scaling
data_fractions: [1.0]
num_subsets: 1

target_modules:
  - "model.decoder.embed_tokens"
  - "model.decoder.embed_positions"
  - "proj_out"
  - "model.decoder.layer_norm"
  - "model.decoder.layers.23"
  - "model.decoder.layers.22"
  - "model.decoder.layers.21"
  - "model.decoder.layers.20"
  - "model.decoder.layers.19"
  - "model.decoder.layers.18"
  - "model.decoder.layers.17"
  - "model.decoder.layers.16"
  - "model.decoder.layers.15"
  - "model.decoder.layers.14"
  - "model.decoder.layers.13"
  - "model.decoder.layers.12"
  - "model.decoder.layers.11"
  - "model.decoder.layers.10"
  - "model.decoder.layers.9"
  - "model.decoder.layers.8"
  - "model.decoder.layers.7"
  - "model.decoder.layers.6"
  - "model.decoder.layers.5"
  - "model.decoder.layers.4"
  - "model.decoder.layers.3"
  - "model.decoder.layers.2"
  - "model.decoder.layers.1"
  - "model.decoder.layers.0"

# Training
output_dir: "outputs/gigaspeech/008/0080"
num_epochs: 1
batch_size: 16
grad_accum_steps: 1
learning_rate: 1e-5
warmup_ratio: 0.01
fp16: true
data_seed: 42
dataloader_num_workers: 8
strict_reproducibility: true

# Evaluation
do_eval: true
eval_steps: 1000
eval_batch_size: 16
